aiku/aiku-common/src/main/java/common/domain/Betting.java, aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleMemberValue.java, aiku/aiku-common/src/main/java/common/response/status/BaseErrorCode.java, aiku/aiku-common/src/test/java/common/domain/BettingTest.java, aiku/aiku-main/src/main/java/aiku_main/controller/BettingController.java, aiku/aiku-main/src/main/java/aiku_main/dto/BettingAddDto.java, aiku/aiku-main/src/main/java/aiku_main/exception/CanNotBettingException.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepository.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustom.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepository.java, aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustom.java, aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleRepositoryCustomImpl.java, aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java
- #13 
<br />
- 베팅 등록 기능 개발 및 통합 테스트
- 베팅 취소 기능 개발 및 통합 테스트
<br />
<br />
=> 베팅 기능 개발 및 통합 테스트

aiku/aiku-common/src/main/java/common/domain/Betting.java, aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java, aiku/aiku-common/src/main/java/common/domain/team/Team.java, aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamBettingResult.java, aiku/aiku-main/src/main/java/aiku_main/application_event/domain/TeamResultMember.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/BettingHandler.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/ScheduleHandler.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TeamHandler.java, aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java, aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingReadRepository.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingReadRepositoryImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustom.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepository.java, aiku/aiku-main/src/main/java/aiku_main/repository/TeamReadRepositoryImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/dto/TeamBettingResultMemberDto.java, aiku/aiku-main/src/main/java/aiku_main/service/BettingService.java, aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java, aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/BettingServiceIntegrationTest.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/ScheduleServiceIntegrationTest.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/TeamServiceIntegrationTest.java
- #19 
<br />
- 그룹 퇴장 시 그룹 분석의 isTeamMember 필드 수정 로직 개발
- 그룹의 지각 분석 결과 조회 기능 개발 및 통합 테스트
- 스케줄 자동 종료Event 발생시 그룹의 지각 분석 로직 개발 및 통합 테스트
- 스케줄 베팅 결과 조회 기능 개발
<br />
<br />
=> 그룹 베팅 결과 분석에 관한 로직 개발

.gitignore, aiku/aiku-common/src/main/java/common/domain/ServiceAgreement.java, aiku/aiku-common/src/main/java/common/domain/member/Member.java, aiku/aiku-common/src/main/java/common/domain/member/MemberProfile.java, aiku/aiku-main/src/main/java/aiku_main/controller/MemberController.java, aiku/aiku-main/src/main/java/aiku_main/dto/AuthorityResDto.java, aiku/aiku-main/src/main/java/aiku_main/dto/AuthorityUpdateDto.java, aiku/aiku-main/src/main/java/aiku_main/dto/MemberResDto.java, aiku/aiku-main/src/main/java/aiku_main/dto/MemberUpdateDto.java, aiku/aiku-main/src/main/java/aiku_main/dto/TitleMemberResDto.java, aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepository.java, aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepositoryImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
<br />
- #29 
<br />
- 멤버 정보 조회, 수정, 삭제 로직 추가
- 로그아웃을 통한 RT 삭제
- 메인 타이틀 수정과 보유 타이틀 조회 로직 추가
- 약관 동의 조회 및 수정 로직 추가
<br />
=> 타이틀, 로그아웃, 권한 관리 등 유저와 관련된 기능 추가

aiku/aiku-common/src/main/java/common/domain/member/Member.java, aiku/aiku-gateway/build.gradle, aiku/aiku-gateway/src/main/java/gateway/security/MemberAdaptor.java, aiku/aiku-gateway/src/main/java/gateway/service/CustomMemberDetailsService.java, aiku/aiku-main/build.gradle, aiku/build.gradle
<br />
- #35 
<br />
- Common 모듈에서 Security 의존 제거
- MemberAdaptor 생성시 권한 직접 주입하는 형태로 변경
- 모듈 내 Gradle Security 의존 변경
<br />
=> Common 모듈에서 Security 의존 제거

aiku/aiku-main/src/main/java/aiku_main/repository/BettingReadRepositoryImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/BettingRepositoryCustomImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/MemberReadRepositoryImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleReadRepositoryImpl.java, aiku/aiku-main/src/main/java/aiku_main/repository/TeamRepositoryCustomImpl.java
- #40 
<br />
- mysql에서 BLOB 길이가 65,535 bytes이므로 오류 발생, db내에서 result와 관련된 필드를 MediumBLOB(16MB)으로 변경.
- 집계함수 STRING_AGG을 GROUP_CONCAT으로 수정
- 필요없는 주석 제거
<br />
<br />
=> h2→mysql 변경으로 인한 내장 함수 변경

aiku/aiku-common/src/main/java/common/kafka/AlarmMessage.java
<br />
- #47 
<br />
- AlarmMessage 클래스 추상 클래스로 변경
- 여러 사람에게 메시지 보낼 수 있도록 firebaseToken 변경
<br />
=> AlarmMessage 추상화

aiku/aiku-alarm/src/main/resources/application.yml, aiku/aiku-gateway/src/main/resources/application.yml, aiku/aiku-main/src/main/resources/application.yml, aiku/aiku-map/src/main/resources/application.yml, aiku/aiku-payment/src/main/resources/application.yml
- #67 
<br />
- sql문 로그 주석처리
- spring-gateway패키지의 yml파일에서 라우팅 경로 ip를 환경변수로 변경
- 모든 패키지에 spring log파일 경로 설정
<br />
<br />
=> 배포를 위한 yml파일 수정

aiku/aiku-alarm/Dockerfile, aiku/aiku-gateway/Dockerfile, aiku/aiku-main/Dockerfile, aiku/aiku-map/Dockerfile
- #67 
<br />
- 도커 image build를 위한 Dockerfile 생성
<br />
<br />
=> gateway, main, alarm, map모듈에 Dockerfile 생성

aiku/aiku-main/src/main/java/aiku_main/dto/MemberProfileDto.java, aiku/aiku-main/src/main/java/aiku_main/oauth/dto/OIDCPublicKeyDto.java, aiku/aiku-main/src/main/java/aiku_main/security/CustomUserDetailsService.java, aiku/aiku-main/src/main/java/aiku_main/security/MemberAdaptor.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java
<br />
- #75 
<br />
- 공개키를 받아오는 DTO 필드 추가
- Enum 타입 Validation 문제 해결
- 시큐리티 분리 작업 중 삭제된 CustomUserDetailsService 복구
<br />
=> 공개키를 파싱하지 못하는 문제 해결

aiku/aiku-gateway/src/main/java/gateway/repository/MemberQueryRepositoryImpl.java
=> aiku-gateway의 멤버 레파지토리 필드 오기재 수정

aiku/aiku-main/src/main/java/aiku_main/controller/TeamController.java, aiku/aiku-main/src/main/java/aiku_main/dto/LocationDto.java, aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java, aiku/aiku-main/src/main/java/aiku_main/service/TeamService.java
- #81 
<br />
- 그룹 상세 조회에서 groupId를 Controller에서 RequestParam -> Pathvariable로 수정
-  스케줄 등록시 LocationDto 기본 생성자 없음
-  그룹 , 스케줄 분석에서 TeamService.getTeamLateTimeResult 메서드 내의 Team.getTeamResult()" is null일때 고려
<br />
<br />
=> 그룹, 스케줄 오류 수정

aiku/aiku-alarm/src/main/java/alarm/WebConfiguration.java, aiku/aiku-map/src/main/java/map/WebConfiguration.java
- #84 
<br />
- Filter 빈 등록 시 Config설정 필요 없음. 따라서 Config에서 MdcFilter 제거
<br />
<br />
=> Filter Config설정 오류 수정

aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java, aiku/aiku-main/src/main/java/aiku_main/MainConfiguration.java, aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java
- #89 
<br />
- Team, Schedule, BettingException에 대한 핸들러 개발
- BaseErrorResponse에 스레드 별 고유 아이디 필드 적용
<br />
<br />
=> Team, Schedule, BettingException에 대한 핸들러 개발

aiku/aiku-map/src/main/java/map/controller/MapController.java, aiku/aiku-map/src/main/java/map/dto/LocationResDto.java, aiku/aiku-map/src/main/java/map/dto/MemberProfileDto.java, aiku/aiku-map/src/main/java/map/dto/ScheduleDetailResDto.java, aiku/aiku-map/src/main/java/map/dto/ScheduleMemberResDto.java, aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepository.java, aiku/aiku-map/src/main/java/map/repository/ScheduleQueryRepositoryImpl.java, aiku/aiku-map/src/main/java/map/service/MapService.java, aiku/aiku-map/src/test/java/map/service/MapServiceTest.java
- #107 
<br />
- 맵의 스케줄 상세 조회 기능 개발 및 테스트
<br />
<br />
=> 맵의 스케줄 상세 조회 기능 개발 및 테스트

aiku/aiku-common/src/main/java/common/response/BaseErrorResponse.java, aiku/aiku-main/src/main/java/aiku_main/exception/MainExceptionHandler.java, aiku/aiku-map/src/main/java/map/exception/MapExceptionHandler.java
- #112 
<br />
- BaseErrorResponse반환 대신 ResponseEntity의 HttpStatusCode 지정 후 반환
<br />
<br />
=> ExceptionHandler에서 ResponseEntity 반환

aiku/aiku-common/src/main/java/common/domain/log/BettingPointLog.java, aiku/aiku-common/src/main/java/common/domain/log/EventLog.java, aiku/aiku-common/src/main/java/common/domain/log/PaymentLog.java, aiku/aiku-common/src/main/java/common/domain/log/PointLog.java, aiku/aiku-common/src/main/java/common/domain/log/RacingPointLog.java, aiku/aiku-common/src/main/java/common/domain/log/SchedulePointLog.java, aiku/aiku-common/src/main/java/common/domain/log/ShopPointLog.java, aiku/aiku-common/src/main/java/common/domain/member/Member.java, aiku/aiku-common/src/main/java/common/domain/value_reference/BettingValue.java, aiku/aiku-common/src/main/java/common/domain/value_reference/EventValue.java, aiku/aiku-common/src/main/java/common/domain/value_reference/RacingValue.java, aiku/aiku-common/src/main/java/common/domain/value_reference/ScheduleValue.java, aiku/aiku-common/src/main/java/common/domain/value_reference/ShopProductValue.java, aiku/aiku-common/src/main/java/common/kafka_message/alarm/PointChangeReason.java, aiku/aiku-common/src/main/java/common/kafka_message/alarm/PointChangedMessage.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeEventHandler.java, aiku/aiku-main/src/main/java/aiku_main/repository/MemberRepository.java, aiku/aiku-main/src/main/java/aiku_main/repository/PointLogRepository.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java, aiku/aiku-main/src/main/java/aiku_main/service/PointLogFactory.java, aiku/aiku-main/src/main/java/aiku_main/service/PointLogService.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/PointChangeEventTest.java, aiku/aiku-map/src/main/java/map/service/RacingService.java
<br />
- #111 
<br />
- 멤버의 포인트 필드를 비관적 락으로 업데이트하는 로직 작성
- 포인트 변화를 DB에 로그로 남기기 위한 로직 작성
<br />
- 다양한 PointLog 자식 객체 생성을 위한 PointLogFactory 객체 생성
=> 멤버 포인트 변화 이벤트를 처리하는 로직 작성

aiku/aiku-gateway/src/main/resources/application.yml
- #114 
<br />
- /login/refresh 경로를 main서버로 라우팅
- ddl-auto 를 잠시 create으로 변경
<br />
<br />
=> aiku-gateway에 login/refresh 라우팅 경로 추가 및 ddl auto create 설정

aiku/aiku-gateway/src/main/resources/application.yml, aiku/aiku-main/src/main/resources/application.yml
- #112 
<br />
<br />
/login/refresh의 오류 응답이 code 200으로 나가는 문제 수정중
<br />
=> aiku-main의 ddl-auto create으로 변경

aiku/aiku-main/src/main/java/aiku_main/service/LoginService.java
<br />
- #120 
<br />
- 멤버 로그인 시 멤버 필드에 RT를 업데이트하는 로직 추가
<br />
=> 로그인 시 멤버 RT를 저장하지 않는 문제 해결

aiku/aiku-common/src/main/java/common/domain/member/Member.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberService.java
<br />
- #123 
<br />
- 회원 탈퇴 시 멤버 필드를 수정하도록 변경
<br />
=> 멤버 탈퇴 시 실제 DB 상 삭제가 아닌 필드 수정

aiku/aiku-common/src/main/java/common/kafka_message/alarm/ScheduleAlarmMessage.java, aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java
- #122 
<br />
- AlarmMessage 메세지에 알람을 받을 사용자들의 파이어베이스 토큰이 list로 들어가게끔 변경됨. 따라서 그에 맞게 수정
<br />
- 후에 리팩토링이 필요해 보임
<br />
=> feat : ScheduleService에서 스케줄 관련 알람을 보내기 위한 카프카 메세지 구조 변경 적용

aiku/aiku-main/src/main/java/aiku_main/controller/LoginController.java, aiku/aiku-main/src/main/java/aiku_main/controller/TermController.java, aiku/aiku-main/src/main/java/aiku_main/dto/RefreshTokenDto.java, aiku/aiku-main/src/main/java/aiku_main/service/TermService.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/TermServiceTest.java
<br />
- #133 
<br />
- Refresh Token 전달 방식 쿠키에서 바디로 변경
- 약관 하나씩 전달하도록 수정
- 테스트 수정
<br />
=> RT 및 약관 전달 방식 변경

aiku/aiku-alarm/src/main/java/alarm/controller/MemberMessageController.java, aiku/aiku-alarm/src/main/java/alarm/controller/dto/DataResDto.java, aiku/aiku-alarm/src/main/java/alarm/repository/MemberMessageRepository.java, aiku/aiku-alarm/src/main/java/alarm/service/MemberMessageService.java, aiku/aiku-alarm/src/main/resources/application.yml
<br />
<br />
- 알람 리스트를 전달하는 방식 변경
- 일부 오류 수정
<br />
=> 리스트 전달 방식 변경

aiku/aiku-main/src/main/java/aiku_main/controller/FirebaseController.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberFirebaseService.java, aiku/aiku-main/src/test/java/aiku_main/integration_test/MemberFirebaseServiceTest.java
<br />
- #141 
<br />
- 토큰 저장 방식 PATCH / POST에서 POST로 통일
- 토큰 존재 여부를 검증하는 로직 삭제
<br />
=> FCM 토큰 저장 방식 변경

aiku/aiku-main/src/main/java/aiku_main/controller/ScheduleController.java, aiku/aiku-main/src/main/java/aiku_main/dto/schedule/ScheduleOwnerResDto.java, aiku/aiku-main/src/main/java/aiku_main/dto/schedule/SchedulePreviewResDto.java, aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustom.java, aiku/aiku-main/src/main/java/aiku_main/repository/ScheduleQueryRepositoryCustomImpl.java, aiku/aiku-main/src/main/java/aiku_main/service/ScheduleService.java, aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java
- #147 
<br />
- 스케줄 프리뷰 조회 기능 개발 및 테스트
<br />
<br />
=> 스케줄 프리뷰 조회 기능 개발

aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeEventHandler.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/PointChangeFailEventHandler.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/RacingHandler.java, aiku/aiku-main/src/main/java/aiku_main/application_event/handler/TitleHandler.java, aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberPointChangeFacade.java, aiku/aiku-main/src/main/java/aiku_main/service/MemberRegisterService.java, aiku/aiku-main/src/main/java/aiku_main/service/PointChangeFailSagaService.java, aiku/aiku-main/src/main/java/aiku_main/service/strategy/RacingRollbackStrategy.java, aiku/aiku-main/src/main/java/aiku_main/service/strategy/RollbackProcessor.java, aiku/aiku-main/src/main/java/aiku_main/service/strategy/RollbackStrategy.java, aiku/aiku-main/src/main/java/aiku_main/service/strategy/ScheduleEnterRollbackStrategy.java, aiku/aiku-main/src/test/java/aiku_main/service/PointChangeEventTest.java
<br />
- #154 
<br />
- 기존 이벤트 클래스가 Value 클래스를 의존하고 있던 것을 Long 타입을 받을 수 있도록 변경하면서 생겼던 컴파일 오류 해결
<br />
- 미처 발견 못한 제 파트 오류가 또 있으면 확인 부탁드립니다~!
=> 이벤트 클래스가 Long 타입을 이용하도록 수정

aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java, aiku/aiku-main/src/test/java/aiku_main/service/BettingServiceIntegrationTest.java, aiku/aiku-main/src/test/java/aiku_main/service/ScheduleServiceTest.java, aiku/aiku-main/src/test/java/aiku_main/service/TeamServiceIntegrationTest.java
- #154 
<br />
- 남아있는 모든 컴파일 오류 수정
- 기존 테스트 코드에서 날짜 관련 오류 수정 및 안쓰는 테스트 제거
<br />
테스트 오류가 통과했다 실패했다 반복해서 나타납니다! 확인 부탁드려요!
<br />
=> value object와 event 리팩토링에 따른 컴파일 오류 수정 완료

aiku/aiku-gateway/src/main/java/gateway/security/SecurityConfig.java, aiku/aiku-gateway/src/main/resources/application.yml
- #169 
<br />
- Spring Security에 권한 허용 경로를 /login/sign-in/**으로 변경
- 게이트 웨이 라우팅 경로 변경
<br />
<br />
=> 로그인 추가 경로를 시큐리티, 게이트 웨이에 적용

aiku/aiku-main/src/main/java/aiku_main/kafka/KafkaConsumerService.java, aiku/aiku-main/src/main/java/aiku_main/scheduler/ScheduleScheduler.java, aiku/aiku-main/src/main/java/aiku_main/service/betting/BettingService.java
- #191 
<br />
- BettingService, ScheduleScheduler, KafkaConsumerService 에서 커스텀 Event Publisher제거
- ObjectMapper대신 커스텀한 ObjectMapperUtil을 의존하도록 변경
<br />
<br />
=> BettingService, ScheduleScheduler, KafkaConsumerService 에서 커스텀 Event Publisher제거

aiku/aiku-common/src/main/java/common/domain/betting/Betting.java, aiku/aiku-common/src/main/java/common/domain/schedule/Schedule.java, aiku/aiku-common/src/main/java/common/domain/schedule/ScheduleResult.java, aiku/aiku-common/src/main/java/common/domain/team/Team.java, aiku/aiku-common/src/test/java/common/domain/ScheduleTest.java, aiku/aiku-common/src/test/java/common/domain/TeamTest.java, aiku/aiku-common/src/test/java/common/domain/betting/BettingTest.java, aiku/aiku-common/src/test/java/common/domain/schedule/ScheduleResultTest.java, aiku/aiku-common/src/test/java/common/domain/team/TeamResultTest.java, aiku/aiku-main/src/main/java/aiku_main/service/betting/BettingService.java
- #210 
<br />
- 팀 도메인 단위 테스트 작성
- 스케줄 도메인 단위 테스트 작성
- 기타 코드 리팩토링
<br />
<br />
=> 스케줄, 팀 도메인 단위 테스트 작성
